### Create Report
POST http://localhost:6666/reports/create
content-type: application/json

{
  "company": "ford",
  "model": "mustang",
  "year": 1990,
  "longitude": 43.456,
  "latitude": 48.910,
  "mileage": 4324,
  "price": 50000
}

### Approve Report
PATCH http://localhost:6666/reports/approve/6
content-type: application/json

{
  "approved": true
}

### Get All Reports
GET http://localhost:6666/reports/allReports
content-type: application/json

### Get Estimate
GET http://localhost:6666/reports/estimate?company=ford
content-type: application/json

